server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

management:
  endpoints:
    web:
      exposure:
        include: *
  endpoint:
    health:show-details: always

spring:
  boot:
    admin:
      client:
        url: http://localhost:8090
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
          - Path=/region/**,/customer/**,/customer-image/**
        - id: product-service
          uri: lb://product-service
          predicates:
          - Path=/category/**,/product/**,/product-image/**
        - id: invoice-service
          uri: lb://invoice-service
          predicates:
          - Path=/invoice/**,/cart/**
